### PR TITLE
Merith/fix322

### LINKED ISSUE #272: deal better with case where native user hasn't configures user.name/email
https://discord.com/channels/1019626071097868289/1019626412346445844/1149111198973968437

### LINKED ISSUE #322: [collection of issues] Issues noticed during work on modifying
* [x] [FIXED] Appears native-git relies on `~/.gitconfig` to be pre-configured with a `user.name` and `user.email` value, 
  * PotentialFix: If these settings are not defined, define them in the local repo scope `git config user.email` instead of `git config --global user.email`
    * `user.email: fastback@default.conf`
    * `user.name: fastback`
    * https://pastebin.com/Rp1yum1B
* [x] [FIXED](https://github.com/Merith-TK/fastback/commit/e6b2b872014ec83148392f6c4aab25bd6246ce18) Improperly uses `HOME` variable on windows
  * windows uses `USERPROFILE` instead, 
  * image
  * 
* [x] [Inconsistent] [possibly non-issue] LFS commands fail on windows
  * This appears to be because git4windows does *not* expose `git-lfs` on the PATH, (related: #321)
  * directly running the command does however work, so dont know what is going on there exactly 
  * PotentialFix: Automatically download from official github and force `git-lfs` into path if not found. 
    * UPDATE: Inconsistent? Just tried it while working on issue 2 and it works now so IDFK I guess

NOTE: I am benching my work on allowing automatically fetching a native release of git to the server directory in favor of looking into and correcting these issues

### PR DESCRIPTION
**Pull request by Merith-TK**
Fixes #322 

## Fix: ImproperVariables
* Added a check if host is windows, and to use the proper variables there.
* Visually nothing has changed, output will still look like `HOME: C:/Users/Username`

## Fix: Missing GitConfig Entries prevent commit
* Fixes #272 
* When user.email and user.name are not found, git would fail to commit and throw the error to the logs, while the user would be told both "error running command" AND "backup successful"
* I set these values in the worlds gitconfig on `init` as the following
  * `user.name`: `<fastbackWorldID>`
  * `user.email`: `<fastbackWorldID>@fastback`
* I only do this on init to allow for users *manually* altering the config.

### CODE REVIEW

**Comment by Merith-TK** [comment]
force push done to squash commits and sign commit

**Comment by pcal43** [comment]
Cool, looks good. Thanks

**Review by pcal43 — COMMENTED** [review]
Looks good, thanks.

**Comment by Merith-TK** [comment]
advantage to this is that it actually can be used to help filter commits to a repo based off the world if the user opts to not change it

**Pull request merged**
